### ISSUE TITLE
panic: Unknown type without TypeSec: <ptr..>

### ISSUE THREAD

**Issue by cryptix** [rainingclouds/autobindings#1]
Hey,

I get a panic when I try to run `autobindings` on a go source file like this:

``` go
// item.go
package test

import "errors"

type Item struct {
    A string
    B int
}

var ErrNoSuchItem = errors.New("no such item")
```

```
[cryptix@higgs ~] autobindings item.go
panic: Unknown type without TypeSec: &{var ErrNoSuchItem 0xc20804e280 0 <nil>}

goroutine 1 [running]:
main.generateFieldMap(0x7fff147777a8, 0x7)
        /home/cryptix/go/src/github.com/rainingclouds/autobindings/generator.go:52 +0x2d5
main.main()
        /home/cryptix/go/src/github.com/rainingclouds/autobindings/generator.go:37 +0x15e

goroutine 2 [runnable]:
runtime.forcegchelper()
        /home/cryptix/gotip/src/runtime/proc.go:90
runtime.goexit()
        /home/cryptix/gotip/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /home/cryptix/gotip/src/runtime/mgc0.go:82
runtime.goexit()
        /home/cryptix/gotip/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /home/cryptix/gotip/src/runtime/malloc.go:712
runtime.goexit()
        /home/cryptix/gotip/src/runtime/asm_amd64.s:2232 +0x1

```

I think you need a typename argument. A lot of my files have more than one type definition in them and i'm not even sure why it tried to interact with the variable declaration in this case.

Otherwise great idea and tool! I'm all for automation where it makes sense and this is definitely a mechanical task.

Also a small suggestion: how about a flag for using the import path as argument instead of just the filename?

Package `go/build` makes it quite easy to lookup imports from the `GOPATH` and a filesystem path relative to the current location can be constructed like this:

``` go
// findRelImport tries to find the import string in the $GOPATH
// and constructs a filepath relative to the current wroking directory
func findRelImport(imp string) string {
    p, err := build.Default.Import(imp, "", build.FindOnly)
    checkPanic(err)

    cwd, err := os.Getwd()
    checkPanic(err)

    p.Dir, err = filepath.Rel(cwd, p.Dir)
    checkPanic(err)

    return p.Dir
}
```

This way you can `autobindings github.com/rainingclouds/awesomeproj/store UserInfo` and move the UserInfo type to another file or rename the file without worrying.

**Comment by akshaydeo** [comment]
I will fix the bug on priority. That check was a copy paste error :(.

And indeed a good suggestion. Let me sleep on it and come up with what I have understood and what we can implement :+1:

**Comment by akshaydeo** [comment]
@cryptix  could you test it now ? Your example class is working with the new fix.

**Comment by cryptix** [comment]
@akshaydeo okay the panic is gone. Thanks!!

Now it creates a `_bindings.go` file for each type in the file. :wink:
